version: "3"
services:
  backend:
    build: .
    container_name: 'backend'
    restart: 'always'
    ports:
      - "80:80"
      - "443:443"
    links:
      - database
    volumes:
      - ./src:/var/www/html
      - ./config/php.ini:/usr/local/etc/php/php.ini
      - ./config/vhosts:/etc/apache2/sites-enabled
  database:
    image: mysql:5.7
    container_name: 'database'
    restart: 'always'
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: tiger
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: 'png-phpmyadmin'
    links:
      - database
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
    ports:
      - '8080:80'
    volumes:
      - /sessions
